name: Package and Release
# Publish a GitHub Release
# Runs on semantic versioned tags only

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  build:
    runs-on: ubuntu-latest
    name: Release
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
